version: "3"

services:
  db:
    build:
      context: ./docker/mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - taskman

  php:
    build:
      context: ./docker/php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ./app/:/var/www/app/
    networks:
      - taskman

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./app/:/var/www/app/
    ports:
      - 80:80
    networks:
      - taskman

volumes:
  db-data:

networks:
  taskman: